nelmio_api_doc:
    documentation:
        host: localhost:8000
        schemes: [http, https]
        info:
            title: Book App
            description: API book avec catégories
            version: 1.0.0
            contact:
                name: "le site du Book"
                url: "http://www.monBook.io/support"
                email: "book@book.com"
        securityDefinitions:
            # permet d'entrer le token au niveau du header lors de la requête
            Bearer:
                type: apiKey
                description: 'Value: Bearer {token}'
                name: Authorization
                in: header
            security:
                - Bearer: []
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api

